version: '3.8'
services:
  app:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      GEMINI_API_KEY: AIzaSyDpr3GFyD6ymHu3A7twES7SCHQoY8KpEA0
      DATABASE: WATERGASMEASUREMENT
      USER: postgres
      PASSWORD: postgres
      HOST: localhost
      PORT: 5432
    command: >
      sh -c "npm install && npm run build && npm run start"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: WATERGASMEASUREMENT
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
